### ISSUE TITLE
VideoSprite not working

### ISSUE THREAD

**Issue by SK7580** [MobilePorting/FNF-PsychEngine-0.7.3-Mobile#2]
### Describe your bug here.

![Screenshot_20241219_183542](https://github.com/user-attachments/assets/46b9bb84-2373-4c2f-8a81-cfb6c23272de)

In the older version that you port the Psych Engine 0.7.3 to android, the VideoHandler works, but since you revived it, it's says about null variable, which will causes issues on NTH208's Pibby Apocalypse Psych Port.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not.

**Comment by mcagabe19** [comment]
we use latest hxCodec so it's `hxcodec.flixel.FlxVideo` and API must be changed aswell so

**Comment by SK7580** [comment]
I did not use 'hxcodec.flixel.FlxVideo'.

**Comment by KarimAkra** [comment]
Then use it
Skill issue

**Comment by SK7580** [comment]
Wait What, it worked, I thought it only works on pc for a second.

**Comment by mcagabe19** [comment]
videos now like same as desktop/pc version
