### ISSUE TITLE
Shaders script error

### ISSUE THREAD

**Issue by SK7580** [MobilePorting/FNF-PsychEngine-0.7.3-Mobile#5]
### Describe your bug here.

![Screenshot_20241221_172941](https://github.com/user-attachments/assets/ad62bd8d-e03d-4ed8-ad59-18c8f007eb8d)
When ever I play a song that used with createShader.lua, it gives me an script error.(createShader.lua scripted by z_myt)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not.

**Comment by mcagabe19** [comment]
can you send the lua file

**Comment by SK7580** [comment]
I can't  because, it does not let me, you can find it in the Mario's Madness V2 Lua Port, Impostor V4 Mods Floder, or Voiid Chronicles.

**Comment by mcagabe19** [comment]
I have neither of those so if u can't provide me the scripts, I'll have to close this issue as wontfix

**Comment by SK7580** [comment]
The code is this.

function runShaderCamera(camera)
    local cams = {}
    local s = {}
    local code = ''
    if type(camera) == 'table' then
        cams = camera
    elseif type(camera) == 'string' then
        cams = {camera}
    end
    for i, cam in pairs(cams) do
        cam = getCamString(cam)
        if objectShaders[cam] ~= nil  then
            if cam == 'camGame' then
                code = code..'game.camGame'
            elseif cam == 'hud' or cam == 'camHUD' then
                code = code..'game.camHUD'
            elseif cam == 'other' or cam == 'camOther' then
                code = code..'game.camOther'
            elseif luaSpriteExists(cam) then
                code = code..'game.getLuaObject("'..cam..'")'
            else
                if version > '0.6.3' and getVar(cam) ~= nil or version == '0.6.3' and runHaxeCode([[return getVar("]]..cam..[[") != null;]]) then
                    code = code..'getVar('..cam..')'
                else
                    goto continue
                end
            end
            local shaders = ''
            for i, shader in pairs(objectShaders[cam]) do
                shaders = shaders..'new ShaderFilter(game.getLuaObject("'..shader..'").shader)'
                if i < #objectShaders[cam] then
                    shaders = shaders..','
                end
            end
            code = code..'.setFilters(['..shaders..']);'
        end
        --runHaxeCode(code)
        
        code = code..'\n'
        ::continue::
    end

    if code ~= '' then
        --code = code..'return;'
        runHaxeCode(code)
    end
end

**Comment by mcagabe19** [comment]
line's are missing, can't u just send as file

**Comment by SK7580** [comment]
I figured it out now
[lua.zip](https://github.com/user-attachments/files/18254486/lua.zip)

**Comment by mcagabe19** [comment]
[createShader.txt](https://github.com/user-attachments/files/18254512/createShader.txt)

try this

**Comment by SK7580** [comment]
It worked out.

**Comment by mcagabe19** [comment]
closing as resolved

**Comment by SK7580** [comment]
![Screenshot_20241226_175411](https://github.com/user-attachments/assets/dd5ca506-a99f-4b83-9109-ff93be2af352)
WHAT IS THIS MESS!!!🤯

**Comment by moxie-coder** [comment]
> ![Screenshot_20241226_175411](https://private-user-images.githubusercontent.com/134719321/398779914-dd5ca506-a99f-4b83-9109-ff93be2af352.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMzYxMDgsIm5iZiI6MTczNTIzNTgwOCwicGF0aCI6Ii8xMzQ3MTkzMjEvMzk4Nzc5OTE0LWRkNWNhNTA2LWE5OWYtNGI4My05MTA5LWZmOTNiZTJhZjM1Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxNzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDFlYThmNDFlZTg2ZDM4ZDZmNTFlYjVlNjJhMTU4ZjE1M2UxNTJiMGE4NThjNTgxZTE1Y2FmMmI4NjdiNTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ovlcNLAACOrP7-D0ch0_Vzmq8akAtDfBX6_nhY06RGU) WHAT IS THIS MESS!!!🤯

as this is no longer related to the issue, I'm locking this
