### ISSUE TITLE
Open the keyboard in a lua script

### ISSUE THREAD

**Issue by Shiho-cmd** [MobilePorting/FNF-PsychEngine-0.7.3-Mobile#6]
### Describe your problem here.

I'm making a port of my mod to mobile but there's some stuff that work better with a keyboard not a custom virtual pad button so i tried looking in the source code for some help but didn't find anything If u guys help It would be a HUGE help!!!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

0.7.x or older

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
what about u set `FlxG.stage.window.textInputEnabled` to true

**Comment by Shiho-cmd** [comment]
> what about u set `FlxG.stage.window.textInputEnabled` to true

It works!!! But the i assume the keyboardPressed function only works with a computer keyboard cruz i tried and It didn't work
Is there a alternative to that that works with the phone keyboard? If no thanks anyways!!

**Comment by mcagabe19** [comment]
I mean can't you use extra controls, we have 2 extra buttons and it can be configured
https://github.com/MobilePorting/FNF-PsychEngine-0.7.3-Mobile/wiki/Mobile-Lua-API

**Comment by Shiho-cmd** [comment]
> I mean can't you use extra controls, we have 2 extra buttons and it can be configured
> https://github.com/MobilePorting/FNF-PsychEngine-0.7.3-Mobile/wiki/Mobile-Lua-API

OOOH I DIDN'T KNOW ABOUT THAT I'M SO SORRY
I was coding the touch controls with mouse and hitbox stuff like that omg so sorry again thank you so much!! will Definitely use that
